version: "3"
services:
    document-server:
        build:
            context: Document-service
            dockerfile: Dockerfile
        image: nkrsingh/myapps:document-server-1.0.0-snapshot     
        ports:
            - 5000:5000
        restart: always
    hello-docker:
        build:
            context: hello-docker
            dockerfile: Dockerfile
        image: nkrsingh/myapps:hello-docker-1.0.0-snapshot       
        ports:
            - 9080:9080
        restart: always
    nodejs-hello-world:
        build:
            context: nodejs-hello-world
            dockerfile: Dockerfile
        image: nkrsingh/myapps:nodejs-hello-world-1.0.0-snapshot      
        ports:
            - 8080:8080
        restart: always
    pyshop:
        build:
            context: pyshop
            dockerfile: Dockerfile
        image: nkrsingh/myapps:pyshop-1.0.0-snapshot   
        ports:
            - 8000:8000
        restart: always

