version: "3"
services:
    document-server:
        build:
            context: Document-service
            dockerfile: Dockerfile
        image: nkrsingh/myapps/document-server:latest      
        ports:
            - 5000:5000
        restart: always
    hello-docker:
        build:
            context: hello-docker
            dockerfile: Dockerfile
        image: nkrsingh/myapps/hello-docker:latest        
        ports:
            - 9080:9080
        restart: always
    nodejs-hello-world:
        build:
            context: nodejs-hello-world
            dockerfile: Dockerfile
        image: nkrsingh/myapps/nodejs-hello-world:latest      
        ports:
            - 8080:8080
        restart: always
    pyshop:
        build:
            context: pyshop
            dockerfile: Dockerfile
        image: nkrsingh/myapps/pyshop:latest   
        ports:
            - 8000:8000
        restart: always

