kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: nodejs-apps
  name: nodejs-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-apps
  template:
    metadata:
      labels:
        app: nodejs-apps
    spec:
      containers:
      - name: nodejs-apps
        imagePullPolicy: Always
        image: nkrsingh/myapps:nodejs-apps-1.0.0
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: mycred
---
kind: Service
apiVersion: v1
metadata: 
  labels:
    app: nodejs-apps
  name: nodejs-apps
spec:
  type: NodePort 
  ports: 
    - port: 80
      targetPort: 5000
      nodePort: 31040
  selector: 
    app: nodejs-apps       